export const ACTIONSFLOW_WORKFLOW_FILE_NAME = `actionsflow.yml`;
export const ARTIFACTS_NAME_PREFIX_FOR_CACHE_KEY = "ACTIONSFLOW_CACHE_KEY____";
export const CACHE_PATH = ".cache";
export const ACTIONSFLOW_LAST_CACHE_KEY = `ACTIONSFLOW_LAST_CACHE_KEY`;
export const ACTIONSFLOW_LATEST_CACHE_KEY = `ACTIONSFLOW_LATEST_CACHE_KEY`;
export const ACTIONSFLOW_CACHE_KEY_PREFIX = `actionsflow-cache-key`;
export const ACTIONSFLOW_NODE_MODULES_CACHE_KEY_PREFIX = `actionsflow-node-modules-cache-key`;
export const ACTIONSFLOW_INITIAL_CACHE_KEY = `ACTIONSFLOW_INITIAL_CACHE_KEY`;
export const ACTIONSFLOW_CACHE_KEY_FILE_NAME = "actionsflow-cache-key.txt";
export const NODE_MODULES_HASH_FILE_PATH = "**/package-lock.json";
export const ACTIONSFLOW_NODE_MODULES_CACHE_RESULT_KEY =
  "ACTIONSFLOW_NODE_MODULES_CACHE_RESULT_KEY";
export const ACTIONSFLOW_NODE_MODULES_CACHE_KEY =
  "ACTIONSFLOW_NODE_MODULES_CACHE_KEY";
export const ACTIONSFLOW_CACHE_RESULT_KEY = "ACTIONSFLOW_CACHE_RESULT_KEY";
export const ACTIONSFLOW_LAST_UPDATE_AT = "ACTIONSFLOW_LAST_UPDATE_AT";
export const ACTIONSFLOW_CURRENT_RUN_CREATED_AT =
  "ACTIONSFLOW_CURRENT_RUN_CREATED_AT";
